-- GENERATED FILE - do not edit by hand.
-- Source: data/procedures-seed.json
-- Regenerate: node scripts/generate-procedures-seed.mjs
--
-- NOT APPLIED to the live database. Run supabase/migrations/008_procedures.sql
-- first, then run this file in the Supabase SQL editor.
--
-- Rows are upserted by id, so re-running is safe and leaves field
-- suggestions alone. Rows dropped from the JSON are NOT deleted here.

begin;

insert into public.chemicals (id, name, epa_number, category, repellency, mix_ratios, notes) values
  ('chem-taurus-sc', 'Taurus SC', '53883-279', 'General Pest - Exterior', 'non-repellent', '[{"context":"Standard mix (backpack sprayer)","ratio":"0.8 fl oz / 1 gal water"},{"context":"Exterior perimeter - March/April rotation","ratio":"0.8 fl oz / 1 gal water"},{"context":"Exterior perimeter - July/August rotation","ratio":"0.8 fl oz / 1 gal water"}]'::jsonb, 'Fipronil non-repellent. Ants cannot detect it, so they carry it back to the colony - excellent on ants, not as effective on other pests. Label restrictions you must follow: maximum 2 applications per year, and no application further than 1 ft from the structure. Apply with a dedicated non-repellent backpack sprayer to prevent contamination with repellent products. Listed on the technician cheat sheet alongside the termiticide products; the Single Family procedure uses it as the exterior perimeter non-repellent in the seasonal rotation. The source procedure marks the Taurus SC application standard as pending internal discussion.'),
  ('chem-termidor-he', 'Termidor HE', '7969-329', 'Termite', 'non-repellent', '[{"context":"Standard mix","ratio":"1.6 fl oz / 1 gal water"}]'::jsonb, 'Termiticide. High-efficiency fipronil formulation for termite trenching and treatment. Follow label and state regulations for volume per linear foot.'),
  ('chem-sentricon-recruit-hd', 'Sentricon Recruit HD', '62719-608', 'Termite', 'n/a', '[{"context":"Station placement (not a mixed product)","ratio":"1 station / 10 ft"}]'::jsonb, 'Termite baiting system. Placement rate, not a dilution - install one station every 10 ft around the structure.'),
  ('chem-suspend-sc', 'Suspend SC', NULL, 'General Pest - Exterior', 'repellent', '[{"context":"Exterior perimeter application","ratio":"0.75 fl oz / 1 gal water"}]'::jsonb, 'Deltamethrin repellent residual. Do not apply over a non-repellent treatment or a granular bait - it will contaminate them.'),
  ('chem-suspend-polyzone', 'Suspend Polyzone', NULL, 'General Pest - Exterior', 'repellent', '[{"context":"Standard mix (cheat sheet general list)","ratio":"1 fl oz / 1 gal water"},{"context":"Exterior perimeter application","ratio":"0.75 fl oz / 1 gal water"}]'::jsonb, 'DISCREPANCY: the technician cheat sheet lists Suspend Polyzone at 1 fl oz per gallon in the general product list and at 0.75 fl oz per gallon under Exterior Perimeter Application. Both are recorded here - confirm which rate applies to your job with your Service Manager. The source also marks this product with an asterisk but gives no matching footnote. Repellent - do not apply over non-repellents or baits.'),
  ('chem-demand-cs', 'Demand CS', NULL, 'General Pest - Exterior', 'repellent', '[{"context":"Exterior perimeter application","ratio":"0.4 fl oz / 1 gal water"}]'::jsonb, 'Lambda-cyhalothrin capsule suspension, repellent. Named in the Single Family procedure as the example of what NOT to spray over a non-repellent ant treatment.'),
  ('chem-onslaught-fastcap', 'Onslaught FastCap', NULL, 'General Pest - Exterior', 'repellent', '[{"context":"Standard mix","ratio":"1 fl oz / 1 gal water"},{"context":"Exterior perimeter - May/June rotation","ratio":"1.0 fl oz / 1 gal water"},{"context":"Exterior perimeter - September/October rotation","ratio":"1.0 fl oz / 1 gal water"}]'::jsonb, 'Long-lasting pyrethroid residual spray. May be substituted for stubborn pests on exterior treatments. Repellent - keep off areas treated with Niban or a non-repellent.'),
  ('chem-pro-flex', 'Pro-Flex', NULL, 'IGR', 'n/a', '[{"context":"Standard mix","ratio":"1 fl oz / 1 gal water"}]'::jsonb, 'Listed on the technician cheat sheet at 1 fl oz per gallon with no application context given, grouped next to Tekko Pro. Confirm target pest, site, and placement with your Service Manager before use.'),
  ('chem-tekko-pro', 'Tekko Pro', NULL, 'IGR', 'n/a', '[{"context":"Standard mix","ratio":"1 fl oz / 1 gal water"}]'::jsonb, 'Insect growth regulator. Breaks the reproductive cycle rather than killing adults, so pair it with a residual or bait. No repellency concern.'),
  ('chem-fipronil-plus-c', 'Fipronil Plus-C', NULL, 'General Pest - Exterior', 'non-repellent', '[{"context":"Service calls for ants / roaches - exterior spot treatment only","ratio":"0.75 fl oz / 1 gal water"}]'::jsonb, 'Exterior SPOT treatment only - not a full perimeter product. Non-repellent, so use a dedicated non-repellent sprayer and do not spray a repellent over it.'),
  ('chem-gentrol-igr', 'Gentrol IGR', NULL, 'IGR', 'n/a', '[{"context":"Interior general pest - Accusprayer (16 fl oz)","ratio":"0.125 fl oz / 16 fl oz water"},{"context":"Interior general pest - backpack power sprayer (1 gal)","ratio":"1 fl oz / 1 gal water"}]'::jsonb, 'Hydroprene growth regulator for interior work. 16 fl oz mixes are solely for the Accusprayer; 1 gallon mixes are primarily for the backpack power sprayer. Pair with Alpine WSG for German roaches.'),
  ('chem-alpine-wsg', 'Alpine WSG', NULL, 'General Pest - Interior', 'non-repellent', '[{"context":"Interior general pest - Accusprayer (16 fl oz)","ratio":"2.5 g / 16 fl oz water"},{"context":"Interior general pest - backpack power sprayer (1 gal)","ratio":"20 g / 1 gal water"},{"context":"Cleanout for active infestation (1 gal)","ratio":"10 g / 1 gal water"}]'::jsonb, 'DISCREPANCY: the cheat sheet lists Alpine WSG at 20 g per gallon under Interior General Pest Control and again at 10 g per gallon in the active-infestation cleanout section. Both rates are recorded here - confirm which applies with your Service Manager before mixing. Dinotefuran, non-repellent: roaches walk through treated areas unknowingly and transfer lethal doses back to the harborage. For German roaches, Alpine WSG plus Gentrol IGR is the preferred pure non-repellent approach. The source also marks this product with an asterisk but gives no matching footnote.'),
  ('chem-ridesco-wg', 'Ridesco WG', NULL, 'Cleanout / Infestation', 'non-repellent', '[{"context":"Cleanout for active infestation - Accusprayer (16 fl oz)","ratio":"2.5 g / 16 fl oz water"},{"context":"Cleanout for active infestation - backpack power sprayer (1 gal)","ratio":"20 g / 1 gal water"}]'::jsonb, 'Used for cleanouts, initial services, and callbacks on active ant and roach infestations, interior and exterior. Per the cheat sheet, non-repellents are used on the outside exclusively and Ridesco WG is the non-repellent for that. Active infestation work must be performed by a certified technician.'),
  ('chem-barricor', 'Barricor', NULL, 'General Pest - Exterior', 'repellent', '[{"context":"Exterior perimeter - January/February rotation","ratio":"0.5 fl oz / 1 gal water"},{"context":"Exterior perimeter - November/December rotation","ratio":"0.5 fl oz / 1 gal water"}]'::jsonb, 'Long-lasting pyrethroid residual spray and the standard for exterior perimeter treatments. Repellent - do not apply over Niban granular bait or a non-repellent treatment.'),
  ('chem-niban', 'Niban', NULL, 'Granular Bait', 'n/a', '[{"context":"Perimeter conducive areas (per home)","ratio":"about 0.5 lb per home"},{"context":"Treated band width","ratio":"approximately 4 ft wide in conducive areas"}]'::jsonb, 'Long-lasting granular bait for conducive areas: shrub beds along the home, AC drip lines, wet areas, near trash cans. Slow to work but lasts 2-3 months and works on a wide variety of pests. Apply only where Barricor, Onslaught FastCap, or Taurus SC was NOT sprayed, to prevent bait contamination.'),
  ('chem-fasttrac-blox', 'Fasttrac Blox', NULL, 'Rodent', 'n/a', '[{"context":"Initial station loading","ratio":"4 blox per station"},{"context":"Maintenance - light activity","ratio":"minimum 2 blox per station"},{"context":"Bait completely consumed / heavy activity","ratio":"up to 8 blox per station"}]'::jsonb, 'Standard rodent bait. Works after only one feeding; rodents die in 5-7 days. Use only inside child and pet resistant Protecta Evo stations. Replace bait if it is consumed, moldy, or otherwise deteriorated. Never leave bait unsecured - replace a broken or unsecured station immediately.')
on conflict (id) do update set
  name = excluded.name,
  epa_number = excluded.epa_number,
  category = excluded.category,
  repellency = excluded.repellency,
  mix_ratios = excluded.mix_ratios,
  notes = excluded.notes;

insert into public.procedures (id, slug, title, summary, category, frequency, sort, updated_at) values
  ('proc-residential-service', 'residential-pest-plus-rodent-service', 'Residential Pest Control Plus Rodent Service Process', 'The six-step field workflow for a residential pest and rodent visit, from route verification through closing the job in the system. Follow this on every scheduled residential service.', 'Service Workflow', 'Every scheduled visit', 1, '2026-07-20'),
  ('proc-single-family', 'single-family-pest-prevention', 'Single Family Home Pest Prevention Procedure', 'The master exterior-based prevention procedure for single family homes: program coverage, initial inspection, preventative perimeter treatment, rodent stations for Plus customers, and the seasonal chemical rotation.', 'Service Procedures', '4x per year', 2, '2026-07-20')
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  summary = excluded.summary,
  category = excluded.category,
  frequency = excluded.frequency,
  sort = excluded.sort,
  updated_at = excluded.updated_at;

insert into public.procedure_sections (id, procedure_id, title, position) values
  ('sec-rs-scope', 'proc-residential-service', 'Scope & Purpose', 1),
  ('sec-rs-route', 'proc-residential-service', '1. Verify Route', 2),
  ('sec-rs-contact', 'proc-residential-service', '2. Contact Customer', 3),
  ('sec-rs-arrival', 'proc-residential-service', '3. Arrival at Customer Premise', 4),
  ('sec-rs-inspection', 'proc-residential-service', '4. Property Inspection', 5),
  ('sec-rs-treatment', 'proc-residential-service', '5. Treatment', 6),
  ('sec-rs-end', 'proc-residential-service', '6. End of Service', 7),
  ('sec-sf-overview', 'proc-single-family', 'Overview & Programs', 1),
  ('sec-sf-initial', 'proc-single-family', 'Initial Visit & Inspection', 2),
  ('sec-sf-preventative', 'proc-single-family', 'Preventative Treatments', 3),
  ('sec-sf-rodent', 'proc-single-family', 'Rodent Stations (Plus Add-on)', 4),
  ('sec-sf-rotation', 'proc-single-family', 'Seasonal Chemical Rotation', 5),
  ('sec-sf-finished', 'proc-single-family', 'When Finished', 6),
  ('sec-sf-materials', 'proc-single-family', 'Materials & Equipment', 7),
  ('sec-sf-education', 'proc-single-family', 'Customer Education', 8)
on conflict (id) do update set
  procedure_id = excluded.procedure_id,
  title = excluded.title,
  position = excluded.position;

insert into public.procedure_steps (id, section_id, content, kind, indent, position, chemical_ids) values
  ('step-rs-001', 'sec-rs-scope', 'Who: technicians performing residential pest and rodent services.', 'step', 0, 1, '[]'::jsonb),
  ('step-rs-002', 'sec-rs-scope', 'What: conduct a full residential pest and rodent service, including inspection, treatment, and recommendations for additional services.', 'step', 0, 2, '[]'::jsonb),
  ('step-rs-003', 'sec-rs-scope', 'When: during scheduled service appointments, typically recurring or one-time services as assigned.', 'step', 0, 3, '[]'::jsonb),
  ('step-rs-004', 'sec-rs-scope', 'Where: customer premises - residential properties requiring pest and rodent management.', 'step', 0, 4, '[]'::jsonb),
  ('step-rs-005', 'sec-rs-scope', 'Why: to deliver consistent, high-quality pest control that protects customer homes and properties from pests and rodents, keeps documentation accurate, supports recommendations for future services, and maintains safety, efficiency, and professionalism throughout the visit.', 'step', 0, 5, '[]'::jsonb),
  ('step-rs-006', 'sec-rs-route', 'Confirm the customer address and name.', 'step', 0, 1, '[]'::jsonb),
  ('step-rs-007', 'sec-rs-route', 'Ensure all required chemicals and equipment are on hand before you leave.', 'step', 0, 2, '[]'::jsonb),
  ('step-rs-008', 'sec-rs-route', 'Check which product the seasonal rotation calls for this month before you load the truck - see the Seasonal Chemical Rotation section of the Single Family Home Pest Prevention procedure.', 'tip', 0, 3, '["chem-barricor","chem-taurus-sc","chem-onslaught-fastcap"]'::jsonb),
  ('step-rs-009', 'sec-rs-contact', 'Call the customer to:', 'step', 0, 1, '[]'::jsonb),
  ('step-rs-010', 'sec-rs-contact', 'Provide your estimated time of arrival (ETA).', 'step', 1, 2, '[]'::jsonb),
  ('step-rs-011', 'sec-rs-contact', 'Confirm the expected service time.', 'step', 1, 3, '[]'::jsonb),
  ('step-rs-012', 'sec-rs-contact', 'Ask about parking or access requirements.', 'step', 1, 4, '[]'::jsonb),
  ('step-rs-013', 'sec-rs-contact', 'If there is no response to the call, follow up with a text message.', 'step', 0, 5, '[]'::jsonb),
  ('step-rs-014', 'sec-rs-arrival', 'Back into the driveway.', 'step', 0, 1, '[]'::jsonb),
  ('step-rs-015', 'sec-rs-arrival', 'Check in for the job:', 'step', 0, 2, '[]'::jsonb),
  ('step-rs-016', 'sec-rs-arrival', 'Verify your arrival time in the system.', 'step', 1, 3, '[]'::jsonb),
  ('step-rs-017', 'sec-rs-arrival', 'Update admin with your real-time location.', 'step', 1, 4, '[]'::jsonb),
  ('step-rs-018', 'sec-rs-arrival', 'Knock on the door and introduce yourself:', 'step', 0, 5, '[]'::jsonb),
  ('step-rs-019', 'sec-rs-arrival', 'Explain the estimated duration of the service.', 'step', 1, 6, '[]'::jsonb),
  ('step-rs-020', 'sec-rs-arrival', 'Collect payment if it is not already in the system.', 'step', 1, 7, '[]'::jsonb),
  ('step-rs-021', 'sec-rs-arrival', 'Ask pest control questions to understand the issues both inside and outside the home.', 'step', 0, 8, '[]'::jsonb),
  ('step-rs-022', 'sec-rs-inspection', 'Inspect the property and check for:', 'step', 0, 1, '[]'::jsonb),
  ('step-rs-023', 'sec-rs-inspection', 'Wood rot - important for termite detection.', 'step', 1, 2, '[]'::jsonb),
  ('step-rs-024', 'sec-rs-inspection', 'Rodent feces or other signs of infestation.', 'step', 1, 3, '[]'::jsonb),
  ('step-rs-025', 'sec-rs-inspection', 'Missing vents.', 'step', 1, 4, '[]'::jsonb),
  ('step-rs-026', 'sec-rs-inspection', 'Water leakage around pipes.', 'step', 1, 5, '[]'::jsonb),
  ('step-rs-027', 'sec-rs-inspection', 'Shrubbery or foliage too close to the house.', 'step', 1, 6, '[]'::jsonb),
  ('step-rs-028', 'sec-rs-inspection', 'Wood rot, mud tubes, or damaged sill plates mean a termite inspection, not a general pest treatment. Write it up as a finding and quote a termite service: Termidor HE at 1.6 fl oz per gallon for a liquid treatment, or Sentricon Recruit HD at one station every 10 ft for a baiting system.', 'tip', 0, 7, '["chem-termidor-he","chem-sentricon-recruit-hd"]'::jsonb),
  ('step-rs-029', 'sec-rs-inspection', 'Note anything you find on the ticket as you go. Findings drive the proposal conversation in step 6 and are the record if the customer calls back later.', 'tip', 0, 8, '[]'::jsonb),
  ('step-rs-030', 'sec-rs-treatment', 'De-webbing:', 'step', 0, 1, '[]'::jsonb),
  ('step-rs-031', 'sec-rs-treatment', 'Remove spiderwebs, wasp nests, and mud daubers.', 'step', 1, 2, '[]'::jsonb),
  ('step-rs-032', 'sec-rs-treatment', 'Spraying:', 'step', 0, 3, '[]'::jsonb),
  ('step-rs-033', 'sec-rs-treatment', 'Apply a 3 ft by 3 ft barrier around the home.', 'step', 1, 4, '["chem-barricor","chem-onslaught-fastcap"]'::jsonb),
  ('step-rs-034', 'sec-rs-treatment', 'Barrier width conflict between documents: this workflow specifies a 3 ft by 3 ft barrier, while the Single Family Home Pest Prevention procedure specifies 1 ft up and 1 ft out. Taurus SC''s label prohibits application further than 1 ft from the structure. Follow the product label first, then confirm the company standard with your Service Manager.', 'warning', 1, 5, '["chem-taurus-sc"]'::jsonb),
  ('step-rs-035', 'sec-rs-treatment', 'Spray above the eaves.', 'step', 1, 6, '[]'::jsonb),
  ('step-rs-036', 'sec-rs-treatment', 'Wear the safety gear required by the product label: gloves, goggles, and any other gear the label specifies.', 'warning', 1, 7, '[]'::jsonb),
  ('step-rs-037', 'sec-rs-treatment', 'Granular application:', 'step', 0, 8, '[]'::jsonb),
  ('step-rs-038', 'sec-rs-treatment', 'Spread granules around the property with a granular spreader.', 'step', 1, 9, '["chem-niban"]'::jsonb),
  ('step-rs-039', 'sec-rs-treatment', 'Keep granular bait out of areas you have sprayed with a repellent residual. Spray residue on bait contaminates it and pests will not feed.', 'warning', 1, 10, '["chem-niban","chem-barricor","chem-onslaught-fastcap"]'::jsonb),
  ('step-rs-040', 'sec-rs-treatment', 'Walk around the home to collect all equipment after the treatment.', 'step', 0, 11, '[]'::jsonb),
  ('step-rs-041', 'sec-rs-end', 'Discuss your findings with the customer:', 'step', 0, 1, '[]'::jsonb),
  ('step-rs-042', 'sec-rs-end', 'Highlight any issues found and any opportunities for additional services.', 'step', 1, 2, '[]'::jsonb),
  ('step-rs-043', 'sec-rs-end', 'Present the Residential Pest Proposal for additional services:', 'step', 0, 3, '[]'::jsonb),
  ('step-rs-044', 'sec-rs-end', 'Quote each service.', 'step', 1, 4, '[]'::jsonb),
  ('step-rs-045', 'sec-rs-end', 'Fill out and verify the form.', 'step', 1, 5, '[]'::jsonb),
  ('step-rs-046', 'sec-rs-end', 'Collect the customer''s signature.', 'step', 1, 6, '[]'::jsonb),
  ('step-rs-047', 'sec-rs-end', 'If no signature is obtained in real time, follow up within 24-48 hours.', 'step', 1, 7, '[]'::jsonb),
  ('step-rs-048', 'sec-rs-end', 'Upload the proposal to the customer card.', 'step', 0, 8, '[]'::jsonb),
  ('step-rs-049', 'sec-rs-end', 'Thank the customer and request a review.', 'step', 0, 9, '[]'::jsonb),
  ('step-rs-050', 'sec-rs-end', 'Upload all service notes into the customer card for future reference.', 'step', 0, 10, '[]'::jsonb),
  ('step-rs-051', 'sec-rs-end', 'Close out the job in the system.', 'step', 0, 11, '[]'::jsonb),
  ('step-sf-001', 'sec-sf-overview', 'Service frequency: four times per year.', 'step', 0, 1, '[]'::jsonb),
  ('step-sf-002', 'sec-sf-overview', 'Crescent offers two main general pest service programs: the Essential Pest Prevention program and the Advanced Pest Management program.', 'step', 0, 2, '[]'::jsonb),
  ('step-sf-003', 'sec-sf-overview', 'Add-on services are available for an additional charge, including our Plus service (rodents), mosquito services, and termite services.', 'step', 0, 3, '[]'::jsonb),
  ('step-sf-004', 'sec-sf-overview', 'Any "Plus" designation denotes a customer who has purchased the rodent management add-on for their exterior services.', 'step', 0, 4, '[]'::jsonb),
  ('step-sf-005', 'sec-sf-overview', 'If there is an interior rodent infestation, inspections to verify activity are included free of charge for Plus customers. Otherwise the inspection is $175.00 during normal business hours and $300.00 outside normal business hours.', 'step', 0, 5, '[]'::jsonb),
  ('step-sf-006', 'sec-sf-overview', 'Any customer with a Plus plan is entitled to a 30% discount on rodent related service calls and/or exclusion work.', 'step', 0, 6, '[]'::jsonb),
  ('step-sf-007', 'sec-sf-overview', 'Treatments are EXTERIOR BASED. The service follows Assessment Based Pest Management ideals that implement Integrated Pest Management techniques: we rely heavily on specific treatments and pinpoint placement of products to solve the specific pest issues that arise.', 'step', 0, 7, '[]'::jsonb),
  ('step-sf-008', 'sec-sf-overview', 'Interior treatments are only performed on the initial service, or when interior activity or infestation has been verified by one of our trained professionals.', 'step', 0, 8, '[]'::jsonb),
  ('step-sf-009', 'sec-sf-overview', 'Because the primary treatments are on the exterior, in most cases the customer does not need to be home for service to be rendered.', 'tip', 0, 9, '[]'::jsonb),
  ('step-sf-010', 'sec-sf-overview', 'Essential Pest Prevention covers common crawling pests: most ants, spiders up to 15 feet, earwigs, centipedes, millipedes, crickets, outdoor roaches, silverfish, stinkbugs, Asian lady beetles, and boxelder bugs.', 'step', 0, 10, '[]'::jsonb),
  ('step-sf-011', 'sec-sf-overview', 'Essential excludes bed bugs, German roaches, flying insects, stored product pests, fleas, ticks, carpenter ants, fire ants, wood destroying organisms, stinging insects, and lawn/ornamental pests.', 'step', 1, 11, '[]'::jsonb),
  ('step-sf-012', 'sec-sf-overview', 'Advanced Pest Management includes every pest covered by Essential Pest Prevention, plus interior fruit flies, house flies, and cluster flies, and exterior mud daubers, wasps, yellowjackets, and hornets up to 20 feet high. Rodent prevention stations and maintenance are also included.', 'step', 0, 12, '[]'::jsonb),
  ('step-sf-013', 'sec-sf-overview', 'Advanced excludes bed bugs, German roaches, stored product pests, fleas, ticks, carpenter ants, fire ants, carpenter bees, honeybees, wood destroying organisms, and lawn/ornamental pests.', 'step', 1, 13, '[]'::jsonb),
  ('step-sf-014', 'sec-sf-overview', 'Interior treatments are provided when necessary and/or when requested due to insect evidence. Service includes additional visits at no charge between the normally scheduled visits if insect evidence requires them.', 'step', 0, 14, '[]'::jsonb),
  ('step-sf-015', 'sec-sf-overview', 'Covered areas include the home and all living spaces associated with it, including but not limited to patios, decks, playgrounds, and detached garages.', 'step', 0, 15, '[]'::jsonb),
  ('step-sf-016', 'sec-sf-overview', 'Coverage language for interior service and limited bed bug coverage is still being finalized in the customer agreement. Confirm current contract terms with the office before you promise coverage to a customer.', 'warning', 0, 16, '[]'::jsonb),
  ('step-sf-017', 'sec-sf-initial', 'The customer is most likely starting service because of a current pest issue. Address their current issue first using the appropriate pest specific procedure, then treat the perimeter for pest prevention if it does not conflict with that pest specific procedure.', 'step', 0, 1, '[]'::jsonb),
  ('step-sf-018', 'sec-sf-initial', 'Do not layer a repellent over a non-repellent. For example, if you treat the perimeter for ants with a non-repellent, do not spray a repellent such as Demand CS on top of it.', 'warning', 0, 2, '["chem-demand-cs","chem-taurus-sc"]'::jsonb),
  ('step-sf-019', 'sec-sf-initial', 'Arrive on time. If you are running late or early, call the customer to let them know. This is the customer''s first contact with us for services - make a great first impression and go above and beyond.', 'step', 0, 3, '[]'::jsonb),
  ('step-sf-020', 'sec-sf-initial', 'Interview the customer. Find out what problems they are having and where they are having them. Then, using your flashlight, inspect those areas looking for signs of active infestations.', 'step', 0, 4, '[]'::jsonb),
  ('step-sf-021', 'sec-sf-initial', 'Let the customer know what you are going to do and discuss their expectations.', 'step', 0, 5, '[]'::jsonb),
  ('step-sf-022', 'sec-sf-initial', 'Take this time to educate the customer on what their pest management experience will look like.', 'step', 0, 6, '[]'::jsonb),
  ('step-sf-023', 'sec-sf-initial', 'Check for toys, pet dishes, exposed food, and anything else that needs to be moved before treatment begins.', 'step', 0, 7, '[]'::jsonb),
  ('step-sf-024', 'sec-sf-initial', 'Trees should be cut back a minimum of 10 feet from the home and small shrubs should be at least 6 inches from the building. This gives us room to treat and eliminates additional access points pests may use to enter the home.', 'step', 0, 8, '[]'::jsonb),
  ('step-sf-025', 'sec-sf-initial', 'Look for any condition that may attract insects or provide a home for them: standing water, excess moisture near the house, overgrown landscaping, wood stacked against the house, trash and recycle bins. Note any problems and let the customer know.', 'step', 0, 9, '[]'::jsonb),
  ('step-sf-026', 'sec-sf-initial', 'Keep an eye out for other pests or conditions that may be upsell opportunities, such as termites, bed bugs, or the need for exclusion services.', 'tip', 0, 10, '[]'::jsonb),
  ('step-sf-027', 'sec-sf-preventative', 'On initial treatments only:', 'step', 0, 1, '[]'::jsonb),
  ('step-sf-028', 'sec-sf-preventative', 'You may have specific pests to treat. Follow that pest specific procedure and do those treatments first to address the customer''s concerns.', 'step', 1, 2, '[]'::jsonb),
  ('step-sf-029', 'sec-sf-preventative', 'If the pest specific treatment required baits or non-repellent sprays, be sure not to contaminate them with repellent products when you make your preventative application to the perimeter.', 'warning', 1, 3, '[]'::jsonb),
  ('step-sf-030', 'sec-sf-preventative', 'On the initial service only, also treat interior hot spot areas such as entry points, ground level window sills, kitchens, and bathrooms if needed.', 'step', 1, 4, '[]'::jsonb),
  ('step-sf-031', 'sec-sf-preventative', 'If the customer also has the Plus add-on covering rodents, check for any rodent activity in the attic.', 'step', 1, 5, '[]'::jsonb),
  ('step-sf-032', 'sec-sf-preventative', 'For German roaches, stick with Alpine WSG plus Gentrol IGR. The pure non-repellent approach allows roaches to walk through treated areas unknowingly and transfer lethal doses back to the harborage.', 'tip', 0, 6, '["chem-alpine-wsg","chem-gentrol-igr"]'::jsonb),
  ('step-sf-033', 'sec-sf-preventative', 'For a cleanout on an active infestation, Ridesco WG is the non-repellent used on the exterior exclusively. Active infestation cleanout work must be performed by a certified technician.', 'tip', 0, 7, '["chem-ridesco-wg"]'::jsonb),
  ('step-sf-034', 'sec-sf-preventative', 'On a service call for ants or roaches, Fipronil Plus-C at 0.75 fl oz per gallon is the exterior spot treatment. Spot treatment only - it is not a full perimeter product.', 'tip', 0, 8, '["chem-fipronil-plus-c"]'::jsonb),
  ('step-sf-035', 'sec-sf-preventative', 'On all treatments, knock down any spiderwebs up to 15 feet high with the Webster brush. Spraying webs tends to plaster them to the house, making them more difficult to remove.', 'step', 0, 9, '[]'::jsonb),
  ('step-sf-036', 'sec-sf-preventative', 'As you walk the perimeter knocking down webs, make sure all toys, furniture, grills, and similar items are safely out of the area you will be treating.', 'step', 0, 10, '[]'::jsonb),
  ('step-sf-037', 'sec-sf-preventative', 'For Advanced Pest Management clients, knock down and/or treat any wasp nests at the first floor level.', 'step', 0, 11, '[]'::jsonb),
  ('step-sf-038', 'sec-sf-preventative', 'On all treatments, treat the perimeter of the home with a liquid residual according to the seasonal rotation schedule - see the Seasonal Chemical Rotation section.', 'step', 0, 12, '["chem-barricor","chem-taurus-sc","chem-onslaught-fastcap"]'::jsonb),
  ('step-sf-039', 'sec-sf-preventative', 'Apply the appropriate product as per the label: 1 ft up and 1 ft out, and to all potential pest areas where pests live or may enter the home, as per label and state regulations, including:', 'step', 0, 13, '[]'::jsonb),
  ('step-sf-040', 'sec-sf-preventative', 'The bottom of exterior entry doors and 1 ft up each side. For the garage door you can treat around the entire perimeter as per label directions.', 'step', 1, 14, '[]'::jsonb),
  ('step-sf-041', 'sec-sf-preventative', 'Around windows with gaps - there is no need to spray well-sealing windows.', 'step', 1, 15, '[]'::jsonb),
  ('step-sf-042', 'sec-sf-preventative', 'Around vents, light fixtures, weep holes, and anywhere utility lines pass through exterior walls.', 'step', 1, 16, '[]'::jsonb),
  ('step-sf-043', 'sec-sf-preventative', 'All first floor soffits.', 'step', 1, 17, '[]'::jsonb),
  ('step-sf-044', 'sec-sf-preventative', 'Around garbage and recycle cans.', 'step', 1, 18, '[]'::jsonb),
  ('step-sf-045', 'sec-sf-preventative', 'Around firewood - do not treat the firewood itself.', 'step', 1, 19, '[]'::jsonb),
  ('step-sf-046', 'sec-sf-preventative', 'Do not treat in electrical meters, firewood, children''s play equipment, or near water.', 'warning', 0, 20, '[]'::jsonb),
  ('step-sf-047', 'sec-sf-preventative', 'Taurus SC has specific label restrictions you must follow: a maximum of 2 applications per year, and you cannot go further than 1 ft from the structure.', 'warning', 0, 21, '["chem-taurus-sc"]'::jsonb),
  ('step-sf-048', 'sec-sf-preventative', 'Taurus SC is a non-repellent that ants cannot detect, so they spread it back to their colony. Use a dedicated non-repellent sprayer when applying it to prevent contamination with repellent products.', 'tip', 0, 22, '["chem-taurus-sc"]'::jsonb),
  ('step-sf-049', 'sec-sf-preventative', 'The source procedure flags the Taurus SC application standard as pending internal discussion. Confirm current policy with your Service Manager before deviating from the label.', 'tip', 0, 23, '["chem-taurus-sc"]'::jsonb),
  ('step-sf-050', 'sec-sf-preventative', 'On all treatments, treat with Niban (about 0.5 lb per home) as per the label in conducive areas around the perimeter of the home. Treat areas such as shrub beds along the home, around AC drip lines, wet areas, near trash cans, and other conducive areas. The treatment should be approximately 4 ft wide in conducive areas.', 'step', 0, 24, '["chem-niban"]'::jsonb),
  ('step-sf-051', 'sec-sf-preventative', 'Apply Niban only in areas that were not sprayed with Barricor, Onslaught FastCap, or Taurus SC, to prevent bait contamination.', 'warning', 0, 25, '["chem-niban","chem-barricor","chem-onslaught-fastcap","chem-taurus-sc"]'::jsonb),
  ('step-sf-052', 'sec-sf-preventative', 'We prefer to use insect monitors or baits indoors if the customer requests indoor service but no specific pest is found. If pests are found indoors, follow that pest specific procedure.', 'step', 0, 26, '[]'::jsonb),
  ('step-sf-053', 'sec-sf-rodent', 'Place Protecta Evo Express rodent stations around the perimeter.', 'step', 0, 1, '[]'::jsonb),
  ('step-sf-054', 'sec-sf-rodent', 'Placing stations in conducive areas is more important than even spacing.', 'tip', 0, 2, '[]'::jsonb),
  ('step-sf-055', 'sec-sf-rodent', 'Station counts by perimeter linear footage:', 'step', 0, 3, '[]'::jsonb),
  ('step-sf-056', 'sec-sf-rodent', '200 linear feet or less: place 6 rodent stations (5 Evo Express and 1 Evo Landscape).', 'step', 1, 4, '[]'::jsonb),
  ('step-sf-057', 'sec-sf-rodent', '200-300 linear feet: place 8 rodent stations (6 Evo Express and 2 Evo Landscape).', 'step', 1, 5, '[]'::jsonb),
  ('step-sf-058', 'sec-sf-rodent', '300-400 linear feet: place 12 rodent stations (8 Evo Express and 4 Evo Landscape).', 'step', 1, 6, '[]'::jsonb),
  ('step-sf-059', 'sec-sf-rodent', 'Over 400 linear feet: discuss with your Service Manager.', 'step', 1, 7, '[]'::jsonb),
  ('step-sf-060', 'sec-sf-rodent', 'Protecta Evo Circuit stations can also be used along walkways to eliminate tripping hazards.', 'tip', 0, 8, '[]'::jsonb),
  ('step-sf-061', 'sec-sf-rodent', 'Place 4 Fasttrac Blox in each station initially.', 'step', 0, 9, '["chem-fasttrac-blox"]'::jsonb),
  ('step-sf-062', 'sec-sf-rodent', 'Follow all label directions for proper placement of bait.', 'warning', 0, 10, '["chem-fasttrac-blox"]'::jsonb),
  ('step-sf-063', 'sec-sf-rodent', 'On all treatments, if rodent stations are included in the service:', 'step', 0, 11, '[]'::jsonb),
  ('step-sf-064', 'sec-sf-rodent', 'Check all exterior Protecta Evo stations.', 'step', 1, 12, '[]'::jsonb),
  ('step-sf-065', 'sec-sf-rodent', 'If a station is broken or otherwise not secured, replace it with a new station immediately. Do not leave bait unsecured.', 'warning', 1, 13, '["chem-fasttrac-blox"]'::jsonb),
  ('step-sf-066', 'sec-sf-rodent', 'Replace bait as needed if it is consumed, becomes moldy, or otherwise deteriorates.', 'step', 1, 14, '["chem-fasttrac-blox"]'::jsonb),
  ('step-sf-067', 'sec-sf-rodent', 'For light activity, maintain at least two Fasttrac Blox in each station. If the bait is completely consumed, you can increase this up to eight Fasttrac Blox per station.', 'step', 1, 15, '["chem-fasttrac-blox"]'::jsonb),
  ('step-sf-068', 'sec-sf-rodent', 'Follow all label directions on the bait packaging.', 'step', 1, 16, '["chem-fasttrac-blox"]'::jsonb),
  ('step-sf-069', 'sec-sf-rodent', 'You may also move stations to areas of higher activity if needed.', 'step', 1, 17, '[]'::jsonb),
  ('step-sf-070', 'sec-sf-rotation', 'Treat the perimeter with a liquid residual on the following rotation:', 'step', 0, 1, '[]'::jsonb),
  ('step-sf-071', 'sec-sf-rotation', 'January / February: Barricor at 0.5 oz per gallon - long-lasting pyrethroid.', 'step', 1, 2, '["chem-barricor"]'::jsonb),
  ('step-sf-072', 'sec-sf-rotation', 'March / April: Taurus at 0.8 oz per gallon - non-repellent, slow-acting.', 'step', 1, 3, '["chem-taurus-sc"]'::jsonb),
  ('step-sf-073', 'sec-sf-rotation', 'May / June: Onslaught FastCap at 1.0 oz per gallon - long-lasting pyrethroid.', 'step', 1, 4, '["chem-onslaught-fastcap"]'::jsonb),
  ('step-sf-074', 'sec-sf-rotation', 'July / August: Taurus at 0.8 oz per gallon - non-repellent, slow-acting.', 'step', 1, 5, '["chem-taurus-sc"]'::jsonb),
  ('step-sf-075', 'sec-sf-rotation', 'September / October: Onslaught FastCap at 1.0 oz per gallon - long-lasting pyrethroid.', 'step', 1, 6, '["chem-onslaught-fastcap"]'::jsonb),
  ('step-sf-076', 'sec-sf-rotation', 'November / December: Barricor at 0.5 oz per gallon - long-lasting pyrethroid.', 'step', 1, 7, '["chem-barricor"]'::jsonb),
  ('step-sf-077', 'sec-sf-rotation', 'The rotation schedules Taurus SC twice a year (March/April and July/August), which is the label maximum of 2 applications per year. Do not apply a third Taurus SC treatment in the same calendar year.', 'warning', 0, 8, '["chem-taurus-sc"]'::jsonb),
  ('step-sf-078', 'sec-sf-rotation', 'The rotation deliberately alternates repellent pyrethroids with a non-repellent so ants cannot detect the treatment and carry it back to the colony. Keep a dedicated non-repellent sprayer loaded for the Taurus SC months.', 'tip', 0, 9, '["chem-taurus-sc","chem-barricor","chem-onslaught-fastcap"]'::jsonb),
  ('step-sf-079', 'sec-sf-rotation', 'Exterior perimeter alternates from the chemical cheat sheet if the rotation product is unavailable: Suspend SC at 0.75 fl oz per gallon, Suspend Polyzone at 0.75 fl oz per gallon, or Demand CS at 0.4 fl oz per gallon. All three are repellents - never apply them over a non-repellent treatment or over Niban granular bait.', 'tip', 0, 10, '["chem-suspend-sc","chem-suspend-polyzone","chem-demand-cs","chem-niban"]'::jsonb),
  ('step-sf-080', 'sec-sf-finished', 'Fill out the service ticket as thoroughly as possible, including detailed notes about the services that were performed.', 'step', 0, 1, '[]'::jsonb),
  ('step-sf-081', 'sec-sf-finished', 'For new customers, fill out a Thank You card and give it to the client.', 'step', 0, 2, '[]'::jsonb),
  ('step-sf-082', 'sec-sf-finished', 'Always thank the customer for their business.', 'step', 0, 3, '[]'::jsonb),
  ('step-sf-083', 'sec-sf-materials', 'Barricor - long-lasting residual spray that is the standard for exterior treatments.', 'step', 0, 1, '["chem-barricor"]'::jsonb),
  ('step-sf-084', 'sec-sf-materials', 'Onslaught FastCap - long-lasting residual spray that may be substituted for stubborn pests on exterior treatments.', 'step', 0, 2, '["chem-onslaught-fastcap"]'::jsonb),
  ('step-sf-085', 'sec-sf-materials', 'Taurus SC - applied with a dedicated backpack sprayer up to two times per year to the perimeter to prevent ant problems. Not as good for other pests, but great for ants.', 'step', 0, 3, '["chem-taurus-sc"]'::jsonb),
  ('step-sf-086', 'sec-sf-materials', 'Niban - long-lasting granular bait for conducive areas. Slow to work, but lasts 2-3 months and works on a wide variety of pests.', 'step', 0, 4, '["chem-niban"]'::jsonb),
  ('step-sf-087', 'sec-sf-materials', 'Protecta Evo Express rodent stations - child and pet resistant stations for use with rodenticide if a customer chooses this add-on service.', 'step', 0, 5, '[]'::jsonb),
  ('step-sf-088', 'sec-sf-materials', 'Protecta Evo Landscape rodent stations - child and pet resistant rodent stations camouflaged as a rock.', 'step', 0, 6, '[]'::jsonb),
  ('step-sf-089', 'sec-sf-materials', 'Protecta Evo Circuit stations - child and pet resistant rodent stations camouflaged as a cable box.', 'step', 0, 7, '[]'::jsonb),
  ('step-sf-090', 'sec-sf-materials', 'Fasttrac Blox - our standard rodent bait. Works after only one feeding; rodents die in 5-7 days.', 'step', 0, 8, '["chem-fasttrac-blox"]'::jsonb),
  ('step-sf-091', 'sec-sf-materials', 'Webster brush - used to knock down spiderwebs up to 15 feet high.', 'step', 0, 9, '[]'::jsonb),
  ('step-sf-092', 'sec-sf-materials', 'Equipment to have on the truck:', 'step', 0, 10, '[]'::jsonb),
  ('step-sf-093', 'sec-sf-materials', 'Flashlight.', 'step', 1, 11, '[]'::jsonb),
  ('step-sf-094', 'sec-sf-materials', 'Ladder, if the attic needs to be inspected.', 'step', 1, 12, '[]'::jsonb),
  ('step-sf-095', 'sec-sf-materials', 'Backpack sprayers - one dedicated repellent, one dedicated non-repellent.', 'step', 1, 13, '[]'::jsonb),
  ('step-sf-096', 'sec-sf-materials', 'B&G sprayers - one dedicated repellent, one dedicated non-repellent.', 'step', 1, 14, '[]'::jsonb),
  ('step-sf-097', 'sec-sf-materials', 'Respirator, if needed in an attic or crawlspace.', 'step', 1, 15, '[]'::jsonb),
  ('step-sf-098', 'sec-sf-materials', 'The source procedure flags the equipment list as pending internal discussion. Confirm the current standard truck load-out with your Service Manager.', 'tip', 0, 16, '[]'::jsonb),
  ('step-sf-099', 'sec-sf-education', 'Remember to educate the customer. Remind them that:', 'step', 0, 1, '[]'::jsonb),
  ('step-sf-100', 'sec-sf-education', 'Most pests come from the outside. We can stop most pests with only exterior treatments, so there is no need to treat the interior every time.', 'step', 1, 2, '[]'::jsonb),
  ('step-sf-101', 'sec-sf-education', 'Sticky monitors and baits are preferred if inside treatments are required.', 'step', 1, 3, '[]'::jsonb),
  ('step-sf-102', 'sec-sf-education', 'Severe initial infestations may take several visits to get under control.', 'step', 1, 4, '[]'::jsonb),
  ('step-sf-103', 'sec-sf-education', 'If they have any questions or concerns, it is better to call us - we will come out as soon as possible.', 'step', 1, 5, '[]'::jsonb)
on conflict (id) do update set
  section_id = excluded.section_id,
  content = excluded.content,
  kind = excluded.kind,
  indent = excluded.indent,
  position = excluded.position,
  chemical_ids = excluded.chemical_ids;

commit;
